name: Bug Report
description: "Report a reproducible bug."
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: Example Application
      description: "Here is a link to my Github repo containing a minimal Laravel application which shows my problem:"
  - type: markdown
    attributes:
      value: |
          You can use `composer show` to get package version numbers:
  - type: input
    attributes:
      label: "Version of ysfkaya/filament-phone-input package:"
    validations:
      required: true
  - type: input
    attributes:
      label: "PHP version:"
    validations:
      required: true

